#!/bin/sh

ISH_SHOW_COLOR_arg="\e[33;4m"

ISH_SHOW_COLOR_r="\e[31m"
ISH_SHOW_COLOR_g="\e[32m"
ISH_SHOW_COLOR_y="\e[33m"
ISH_SHOW_COLOR_b="\e[34m"
ISH_SHOW_COLOR_p="\e[35m"
ISH_SHOW_COLOR_c="\e[36m"

ISH_SHOW_COLOR_red="\e[31m"
ISH_SHOW_COLOR_green="\e[32m"
ISH_SHOW_COLOR_blue="\e[34m"
ISH_SHOW_COLOR_yellow="\e[33m"
ISH_SHOW_COLOR_purple="\e[35m"
ISH_SHOW_COLOR_cyan="\e[36m"
ISH_SHOW_COLOR_black="\e[37m"
ISH_SHOW_COLOR_white="\e[30m"
ISH_SHOW_COLOR_bg_red="\e[41m"
ISH_SHOW_COLOR_bg_green="\e[42m"
ISH_SHOW_COLOR_bg_blue="\e[44m"
ISH_SHOW_COLOR_bg_yellow="\e[43m"
ISH_SHOW_COLOR_bg_purple="\e[45m"
ISH_SHOW_COLOR_bg_cyan="\e[46m"
ISH_SHOW_COLOR_bg_black="\e[47m"
ISH_SHOW_COLOR_bg_white="\e[40m"
ISH_SHOW_COLOR_bold="\e[1m"
ISH_SHOW_COLOR_underline="\e[4m"
ISH_SHOW_COLOR_reverse="\e[7m"
ISH_SHOW_COLOR_blink="\e[5m"
ISH_SHOW_COLOR_end="\e[0m"

