" 插件列表"{{{
if filereadable(expand("~/.vim/autoload/plug.vim"))
	call plug#begin()
	Plug 'vim-airline/vim-airline'
	Plug 'airblade/vim-gitgutter'
	Plug 'tpope/vim-fugitive'
	" Plug 'mbbill/echofunc'
	Plug 'kien/ctrlp.vim'
	let g:ctrlp_cmd='CtrlPBuffer'
	" Plug 'majutsushi/tagbar'
	Plug 'scrooloose/nerdtree'
	let g:NERDTreeWinPos="left"
	let g:NERDTreeWinSize=20
	" Plug 'gcmt/taboo.vim'
	" set sessionoptions+=tabpages,globals

	" Plug 'vim-syntastic/syntastic'
	Plug 'vim-scripts/tComment'
	Plug 'fatih/vim-go'
	Plug 'chr4/nginx.vim'
	" Plug 'othree/html5.vim'
	" Plug 'vim-scripts/python.vim'
	" Plug 'plasticboy/vim-markdown'
	" Plug 'vim-scripts/matrix.vim--Yang'
	call plug#end()
endif
"}}}
" 基本配置"{{{
set number
set relativenumber
set cursorcolumn
set cursorline
set scrolloff=3
set cc=120
set nowrap
set mouse=a
" 缩进
set cindent
set tabstop=4
set shiftwidth=4
set backspace=indent,eol,start
" 折叠
set foldenable
set foldmethod=marker
" 搜索
set hlsearch
set incsearch
set nowrapscan
set smartcase
set ignorecase
set showmatch
set matchtime=2
" 缓存
set hidden
set autowrite
set encoding=utf-8
" 按键
nnoremap <Space> :
nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l
"}}}
" 编程配置{{{
set keywordprg=man\ -a
func! Configs()
	let ext = expand("%:e") | if &ft == "" && ext != "" | exec "set" "filetype=" . ext | endif
   	if ext == "json"
		set foldmethod=syntax

	elseif ext == "js"
		set filetype=javascript
		source ~/.vim/syntax/javascript.vim

	elseif ext == "css"
		set foldmethod=marker
		set foldmarker={,}

	elseif ext == "vimrc"
		set filetype=vim

	elseif ext == "conf"
		set filetype=nginx

	elseif ext == "iml"
		set commentstring=#%s

	elseif ext == "zml"
		set commentstring=#%s

	elseif ext == "sql"
		set expandtab
		set foldmarker=(,)

	elseif ext == "proto"
		set expandtab
		set foldmarker={,}

	elseif ext == "groovy"
		set expandtab

	elseif ext == "java"
		set expandtab
		set omnifunc=javacomplete#Complete

	endif
endfunc | autocmd BufNewFile,BufReadPost * call Configs()
"}}}
"本地配置"{{{
for file in ["~/.vim/autoload/auto.vim", "~/.vim_local.vim", "etc/vimrc"]
	if filereadable(expand(file)) | exec "source" file | endif
endfor | autocmd BufReadPost * normal `"
"}}}
"主题色系"{{{
syntax on
set t_Co=256
colorscheme torte
highlight Comment ctermfg=cyan ctermbg=darkblue
highlight PmenuSel ctermfg=darkblue ctermbg=cyan
highlight Pmenu ctermfg=cyan ctermbg=darkblue
"}}}
