" 软件安装 {{{
"$ curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
"1. 安装vim各种插件
":PlugInstall
"
"2. 安装go各种插件
":GoInstallBinaries
"}}}
" 插件列表"{{{
if filereadable(expand("~/.vim/autoload/plug.vim"))
	call plug#begin()

	Plug 'vim-scripts/tComment'
	Plug 'vim-syntastic/syntastic'

	Plug 'vim-airline/vim-airline'
	Plug 'airblade/vim-gitgutter'
	Plug 'tpope/vim-fugitive'
	Plug 'mbbill/echofunc'
	Plug 'kien/ctrlp.vim'
	let g:ctrlp_cmd='CtrlPBuffer'

	Plug 'majutsushi/tagbar'
	Plug 'scrooloose/nerdtree'
	let g:NERDTreeWinPos="left"
	let g:NERDTreeWinSize=20

	Plug 'gcmt/taboo.vim'
	set sessionoptions+=tabpages,globals

	Plug 'fatih/vim-go'
	" Plug 'posva/vim-vue'
	Plug 'chr4/nginx.vim'
	Plug 'othree/html5.vim'
	Plug 'vim-scripts/python.vim'
	Plug 'plasticboy/vim-markdown'
	Plug 'vim-scripts/matrix.vim--Yang'
	call plug#end()
endif
"}}}
" 基本配置"{{{
set cc=120
set nowrap
set number
set relativenumber
set cursorline
set cursorcolumn
set scrolloff=3
set mouse=a

" 缓存
set hidden
set autowrite
set encoding=utf-8

" 搜索
set hlsearch
set incsearch
set nowrapscan
set smartcase
set ignorecase
set showmatch
set matchtime=2

" 缩进
set cindent
" set expandtab
set tabstop=4
set shiftwidth=4
set backspace=indent,eol,start

" 折叠
set foldenable
set foldmethod=marker

" 按键
nnoremap <Space> :
nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l

nnoremap <F2> :NERDTreeToggle<CR>
nnoremap <F3> :TagbarToggle<CR>
"}}}
" 编程配置{{{
set keywordprg=man\ -a

function! Config(type)
	if a:type == "conf"
		set filetype=nginx
	elseif a:type == "xml"
		set filetype=xml
	elseif a:type == "vue"
		set shiftwidth=2
		set tabstop=2
	endif
endfunction

func! Configs()
	let ext = expand("%:e")
	if ext == "go"
		set foldnestmax=3
		set foldmethod=syntax
		let g:tagbar_ctags_bin = "gotags"
		nnoremap <C-[> :GoImplements<CR>

		let g:go_updatetime = 300
		" let g:go_auto_sameids = 0
		let g:go_auto_type_info = 1
		let g:go_version_warning = 0
		
		let g:go_fmt_autosave = 1
		let g:go_imports_autosave = 1
		" let g:go_metalinter_autosave = 1
		
		let g:go_highlight_types = 1
		let g:go_highlight_functions = 1
		let g:go_highlight_operators = 1
		let g:go_highlight_space_tab_error = 1
		let g:go_highlight_trailing_whitespace_error = 1
		
		" au BufWritePost *.go silent call GoFmts()
		" autocmd BufWritePre *.go GoFmt
		" autocmd BufWritePre *.go GoVet
		" autocmd BufWritePre *.go GoLint
		" autocmd BufWritePre *.go GoImports

	elseif ext == "shy"
		set tabstop=2
		set shiftwidth=2
		set commentstring=#%s
		set foldmethod=indent
		set filetype=shy

	elseif ext == "json"
		set foldmethod=syntax

	elseif ext == "sh"
		set foldmethod=marker
		set foldmarker={,}

	elseif ext == "js"
		let javaScript_fold=1
		set foldmethod=marker
		set foldmarker={,}
		set filetype=javascript
		source ~/.vim/syntax/javascript.vim

	elseif ext == "css"
		set filetype=css
		set foldmethod=marker
		set foldmarker={,}
		set shiftwidth=2
		set tabstop=2

	elseif ext == "zml"
		set filetype=zml
		set tabstop=2
		set shiftwidth=2
		set commentstring=#%s

	elseif ext == "iml"
		set filetype=iml
		set tabstop=2
		set shiftwidth=2
		set commentstring=#%s

	elseif ext == "yaml"
		set shiftwidth=2
		set tabstop=2

	elseif ext == "proto"
		set foldmarker={,}
		set shiftwidth=2
		set tabstop=2
		set expandtab

	elseif ext == "sql"
		set foldmarker=(,)
		set shiftwidth=2
		set tabstop=2
		set expandtab

	elseif ext == "groovy"
		set expandtab
		set tabstop=4
		set shiftwidth=4

    elseif ext == "java"
		set expandtab
		set tabstop=4
		set shiftwidth=4
		set omnifunc=javacomplete#Complete

	endif
endfunc

autocmd BufNewFile,BufReadPost * call Configs()
autocmd BufNewFile,BufReadPost *.conf call Config("conf")
autocmd BufNewFile,BufReadPost *.wxml call Config("xml")
autocmd BufNewFile,BufReadPost *.vue call Config("vue")
function! GoFmts()
	!gofmt -w %
	!goimports -w %
	edit!
endfunction
"}}}

"本地配置"{{{
if filereadable(expand("~/.vim/autoload/auto.vim")) | source ~/.vim/autoload/auto.vim | endif
if filereadable(expand("~/.vim_local.vim")) | source ~/.vim_local.vim | endif
if filereadable(expand("etc/vimrc")) | source etc/vimrc | endif
autocmd BufReadPost * normal `"
"}}}
"主题色系"{{{
syntax on
set t_Co=256
colorscheme torte
" colorscheme elflord

highlight Comment ctermfg=cyan ctermbg=darkblue
highlight PmenuSel ctermfg=darkblue ctermbg=cyan
highlight Pmenu ctermfg=cyan ctermbg=darkblue
"}}}
